apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::336349159477:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-17XRJCHTLUNVH
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-01-04T11:41:38Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2021-01-04T11:41:38Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1641"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: c78fbd39-d746-41f2-b1fd-3154e7f6ff64
